"""added revoked attribute to payment

Revision ID: 18c8e4242437
Revises: 7303f95424c1
Create Date: 2018-08-07 16:01:53.711995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18c8e4242437'
down_revision = '7303f95424c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('revoked', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'revoked')
    # ### end Alembic commands ###
