"""facebook_fixes

Revision ID: 1930e8e8eaed
Revises: aa345570d028
Create Date: 2018-07-17 17:56:19.514744

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1930e8e8eaed'
down_revision = 'aa345570d028'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('constant', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('complete_times', sa.Integer(), nullable=False),
    sa.Column('start_timestamp', sa.DateTime(), nullable=True),
    sa.Column('end_timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['action'], ['task_actions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('old_balance', sa.Integer(), nullable=True),
    sa.Column('new_balance', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('balance_logs')
    op.add_column('facebook_connections', sa.Column('oauth_token', sa.String(length=256), nullable=True))
    op.add_column('facebook_connections', sa.Column('requested_timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_facebook_connections_oauth_token'), 'facebook_connections', ['oauth_token'], unique=False)
    op.drop_column('facebook_connections', 'timestamp')
    op.add_column('twitter_connections', sa.Column('authorized_timestamp', sa.DateTime(), nullable=True))
    op.add_column('twitter_connections', sa.Column('requested_timestamp', sa.DateTime(), nullable=True))
    op.drop_column('twitter_connections', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_connections', sa.Column('timestamp', mysql.DATETIME(), nullable=True))
    op.drop_column('twitter_connections', 'requested_timestamp')
    op.drop_column('twitter_connections', 'authorized_timestamp')
    op.add_column('facebook_connections', sa.Column('timestamp', mysql.DATETIME(), nullable=True))
    op.drop_index(op.f('ix_facebook_connections_oauth_token'), table_name='facebook_connections')
    op.drop_column('facebook_connections', 'requested_timestamp')
    op.drop_column('facebook_connections', 'oauth_token')
    op.create_table('balance_logs',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('old_balance', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('new_balance', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='balance_logs_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('payments')
    op.drop_table('tasks')
    op.drop_table('task_actions')
    # ### end Alembic commands ###
