"""edited connections tablenames

Revision ID: 28c300c908ef
Revises: f03fa2e283db
Create Date: 2018-07-20 12:23:28.886562

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '28c300c908ef'
down_revision = 'f03fa2e283db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('facebook_connections', 'connections_facebook')
    op.rename_table('twitter_connections', 'connections_twitter')
    op.rename_table('linkedin_connections', 'connections_linkedin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('connections_facebook', 'facebook_connections')
    op.rename_table('connections_twitter', 'twitter_connections')
    op.rename_table('connections_linkedin', 'linkedin_connections')
    # ### end Alembic commands ###
