"""tables fixes

Revision ID: 2e2ce1e47b80
Revises: 28c300c908ef
Create Date: 2018-07-20 18:08:46.347440

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2e2ce1e47b80'
down_revision = '28c300c908ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connections_facebook', sa.Column('authorized_timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_connections_facebook_oauth_token'), 'connections_facebook', ['oauth_token'], unique=False)
    op.drop_index('ix_facebook_connections_oauth_token', table_name='connections_facebook')
    op.drop_column('connections_facebook', 'requested_timestamp')
    op.create_index(op.f('ix_connections_twitter_oauth_token'), 'connections_twitter', ['oauth_token'], unique=False)
    op.drop_index('ix_twitter_connections_oauth_token', table_name='connections_twitter')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_twitter_connections_oauth_token', 'connections_twitter', ['oauth_token'], unique=False)
    op.drop_index(op.f('ix_connections_twitter_oauth_token'), table_name='connections_twitter')
    op.add_column('connections_facebook', sa.Column('requested_timestamp', mysql.DATETIME(), nullable=True))
    op.create_index('ix_facebook_connections_oauth_token', 'connections_facebook', ['oauth_token'], unique=False)
    op.drop_index(op.f('ix_connections_facebook_oauth_token'), table_name='connections_facebook')
    op.drop_column('connections_facebook', 'authorized_timestamp')
    # ### end Alembic commands ###
