"""added facebook token_type expires_in

Revision ID: 5f05b3a9fd2a
Revises: 1930e8e8eaed
Create Date: 2018-07-18 16:21:19.073776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f05b3a9fd2a'
down_revision = '1930e8e8eaed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facebook_connections', sa.Column('expires_in', sa.DateTime(), nullable=True))
    op.add_column('facebook_connections', sa.Column('token_type', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facebook_connections', 'token_type')
    op.drop_column('facebook_connections', 'expires_in')
    # ### end Alembic commands ###
