"""added task link to post

Revision ID: 6ab37cb0fa4d
Revises: 43eb324e5889
Create Date: 2018-07-23 11:36:43.320595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ab37cb0fa4d'
down_revision = '43eb324e5889'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('link', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'link')
    # ### end Alembic commands ###
