"""employer field

Revision ID: 715dceb18ce6
Revises: 5f05b3a9fd2a
Create Date: 2018-07-18 18:52:07.895225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '715dceb18ce6'
down_revision = '5f05b3a9fd2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('employer', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'employer')
    # ### end Alembic commands ###
