"""init

Revision ID: aa345570d028
Revises:
Create Date: 2018-07-16 18:34:29.225095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa345570d028'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facebook_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('authorized', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('linkedin_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('authorized', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('twitter_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oauth_token', sa.String(length=256), nullable=True),
    sa.Column('oauth_secret_token', sa.String(length=256), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('authorized', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_twitter_connections_oauth_token'), 'twitter_connections', ['oauth_token'])
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=True),
    sa.Column('first_name', sa.String(length=256), nullable=True),
    sa.Column('last_name', sa.String(length=256), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('twitter_id', sa.Integer(), nullable=True),
    sa.Column('facebook_id', sa.Integer(), nullable=True),
    sa.Column('linkedin_id', sa.Integer(), nullable=True),
    sa.Column('referral_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['facebook_id'], ['facebook_connections.id'], ),
    sa.ForeignKeyConstraint(['linkedin_id'], ['linkedin_connections.id'], ),
    sa.ForeignKeyConstraint(['referral_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['twitter_id'], ['twitter_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_tg_user_id'), 'users', ['tg_user_id'], unique=True)
    op.create_table('balance_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('old_balance', sa.Integer(), nullable=True),
    sa.Column('new_balance', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('balance_logs')
    op.drop_index(op.f('ix_users_tg_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('twitter_connections')
    op.drop_table('linkedin_connections')
    op.drop_table('facebook_connections')
    # ### end Alembic commands ###
