"""tasks

Revision ID: b2ce00634091
Revises: 2e2ce1e47b80
Create Date: 2018-07-21 11:48:37.519815

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b2ce00634091'
down_revision = '2e2ce1e47b80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('payments')
    op.add_column('task_actions', sa.Column('name', sa.String(length=64), nullable=True))
    op.drop_column('task_actions', 'constant')
    op.add_column('tasks', sa.Column('action_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('reward', sa.Integer(), nullable=False))
    op.drop_constraint('tasks_ibfk_1', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'task_actions', ['action_id'], ['id'])
    op.drop_column('tasks', 'action')
    op.drop_column('tasks', 'points')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('points', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('action', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_ibfk_1', 'tasks', 'task_actions', ['action'], ['id'])
    op.drop_column('tasks', 'reward')
    op.drop_column('tasks', 'action_id')
    op.add_column('task_actions', sa.Column('constant', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column('task_actions', 'name')
    op.create_table('payments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('amount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('old_balance', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('new_balance', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='payments_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('task_completions')
    # ### end Alembic commands ###
