"""edited connections relationships

Revision ID: f03fa2e283db
Revises: 715dceb18ce6
Create Date: 2018-07-20 11:08:27.789703

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f03fa2e283db'
down_revision = '715dceb18ce6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facebook_connections', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'facebook_connections', 'users', ['user_id'], ['id'])
    op.add_column('linkedin_connections', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'linkedin_connections', 'users', ['user_id'], ['id'])
    op.add_column('twitter_connections', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'twitter_connections', 'users', ['user_id'], ['id'])
    op.drop_constraint('users_ibfk_4', 'users', type_='foreignkey')
    op.drop_constraint('users_ibfk_2', 'users', type_='foreignkey')
    op.drop_constraint('users_ibfk_1', 'users', type_='foreignkey')
    op.drop_column('users', 'twitter_id')
    op.drop_column('users', 'linkedin_id')
    op.drop_column('users', 'facebook_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('facebook_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('linkedin_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('twitter_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('users_ibfk_1', 'users', 'facebook_connections', ['facebook_id'], ['id'])
    op.create_foreign_key('users_ibfk_2', 'users', 'linkedin_connections', ['linkedin_id'], ['id'])
    op.create_foreign_key('users_ibfk_4', 'users', 'twitter_connections', ['twitter_id'], ['id'])
    op.drop_constraint(None, 'twitter_connections', type_='foreignkey')
    op.drop_column('twitter_connections', 'user_id')
    op.drop_constraint(None, 'linkedin_connections', type_='foreignkey')
    op.drop_column('linkedin_connections', 'user_id')
    op.drop_constraint(None, 'facebook_connections', type_='foreignkey')
    op.drop_column('facebook_connections', 'user_id')
    # ### end Alembic commands ###
