"""added twitter and facebook users id

Revision ID: f7c4c4193241
Revises: c6efd9b1839c
Create Date: 2018-08-03 15:57:36.415517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7c4c4193241'
down_revision = 'c6efd9b1839c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connections_facebook', sa.Column('facebook_user_id', sa.String(length=64), nullable=True))
    op.add_column('connections_twitter', sa.Column('twitter_user_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connections_twitter', 'twitter_user_id')
    op.drop_column('connections_facebook', 'facebook_user_id')
    # ### end Alembic commands ###
